import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import StickyFooter from "@/components/footer/StickyFooter";
import { Typography } from "@mui/material";
import Events from "@/components/events/Events";
import Navbar from "@/components/navbar/Navbar";
import Goals from "@/components/goals/Goals";
import GitaContestCarousel from "@/components/carousel/GitaContestCarousel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Gita Life</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* Navbar which contains the ISKCON logo, ISKCON full form and Srila Prabhupada */}
            <Navbar />
            <div
                style={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "center",
                    alignItems: "center",
                    padding: "20px",
                    fontFamily: "'Spectral', serif",
                }}
            >
                {/* Here will be the quiz */}
                {/* Quiz title */}
                <Typography
                    style={{
                        marginTop: "-40px",
                        marginBottom: "40px",
                        textAlign: "center",
                    }}
                    variant="h1"
                    component="h1"
                >
                    Bhagavad Gita Contest
                </Typography>
                {/* Carousel for images and youtube links */}
                <GitaContestCarousel />
                {/* Embedded google form */}
                <iframe
                    src="https://docs.google.com/forms/d/e/1FAIpQLSdQb0GqE--2K3kPQavkCwoUnsmgNpWzcbNLmMzW7G5pRW-iUg/viewform?embedded=true"
                    style={{ alignContent: "center" }}
                    frameBorder="0"
                    height="645px"
                    width="75%"
                >
                    Loading...
                </iframe>
            </div>
            <StickyFooter />
        </>
    );
}
